# --- PR Rules ---

# UI-related files → needs-screenshot
needs-screenshot:
  - any: ['**/*.css', '**/*.scss', '**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '**/*.html']

# Enhancement / feature improvement
enhancement:
  - any: ['features/**', 'src/feature/**', 'src/components/**']

# Level 2 = all enhancements
"Level 2":
  - any: ['features/**', 'src/feature/**', 'src/components/**']

# Major work / new features
major-work:
  - any: ['src/core/**', 'server/**', 'api/**']

# Level 3 = all major work
"Level 3":
  - any: ['src/core/**', 'server/**', 'api/**']

# Documentation changes
documentation:
  - any: ['**/*.md', 'docs/**']

# GSSoC applied to all PRs
"GSSoC'25":
  - any: ['**/*']


# Bug-related paths
bug:
  - any: ['**/bug/**', '**/bugs/**']

# Other labels
duplicate:
  - any: ['**/duplicate/**']

"good first issue":
  - any: ['**/good-first-issue/**']

"help wanted":
  - any: ['**/help-wanted/**']

invalid:
  - any: ['**/invalid/**']

question:
  - any: ['**/question/**', '**/questions/**']

wontfix:
  - any: ['**/wontfix/**']
