bug:
  - any: ['**/bug/**', '**/bugs/**']
    
documentation:
  - any: ['**/*.md', '**/docs/**', '**/documentation/**']
    
duplicate:
  - any: ['**/duplicate/**']
    
enhancement:
  - any: ['**/enhancement/**', '**/features/**']
    
"good first issue":
  - any: ['**/good-first-issue/**']
    
"GSSoC'25":
  - any: ['**/*gssoc*/**', '**/*GSSoC*/**']
    
"help wanted":
  - any: ['**/help-wanted/**']
    
invalid:
  - any: ['**/invalid/**']
    
"Level 3":
  - any: ['**/level3/**', '**/Level3/**']
    
question:
  - any: ['**/question/**', '**/questions/**']
    
wontfix:
  - any: ['**/wontfix/**']
    
Development:
  - any: ['**/src/**', '**/frontend/**', '**/backend/**', '**/components/**']
