bug:
  - 'bug'
documentation:
  - '**/*.md'
duplicate:
  - 'duplicate'
enhancement:
  - 'enhancement'
good first issue:
  - 'good first issue'
GSSoC25:
  - "GSSoC'25"
help wanted:
  - 'help wanted'
invalid:
  - 'invalid'
Level3:
  - 'Level 3'
question:
  - 'question'
wontfix:
  - 'wontfix'
Development:
  - 'development'
