"bug":
  - "src/**/bug*"
  - "**/bug*"

"documentation":
  - "docs/**"
  - "**/*.md"

"enhancement":
  - "src/**/feature*"
  - "**/feature*"

"good first issue":
  - "good-first-issue/**"
  - "**/good-first-issue*"

"help wanted":
  - "help-wanted/**"
  - "**/help-wanted*"
