# --- Pull Request Rules ---

# Add "needs-screenshot" if UI-related files are changed
needs-screenshot:
  - '**/*.css'
  - '**/*.scss'
  - '**/*.js'
  - '**/*.jsx'
  - '**/*.ts'
  - '**/*.tsx'
  - '**/*.html'

# Add "documentation" if docs are changed
documentation:
  - '**/*.md'
  - 'docs/**'

# Add "enhancement" if feature code is touched
enhancement:
  - 'features/**'
  - 'src/feature/**'

# Mark as "good first issue" if beginner-friendly files are touched
good first issue:
  - 'examples/**'
  - 'tutorials/**'

# Apply "GSSoC'25" if contributions are in GSSoC scope
"GSSoC'25":
  - 'gssoc/**'

# --- Issue Rules ---

# Bug reports (title starts with [BUG])
bug:
  - 'issues: ["^\\[BUG\\]"]'

# Feature requests (title starts with [Feature])
enhancement:
  - 'issues: ["^\\[Feature\\]"]'

# Documentation requests (title contains [Docs] or [Doc])
documentation:
  - 'issues: ["(?i)\\[docs?\\]"]'

# Questions (title starts with [Question])
question:
  - 'issues: ["^\\[Question\\]"]'

# Mark invalid if title contains [Invalid]
invalid:
  - 'issues: ["\\[Invalid\\]"]'
