bug:
  - "bug"
  - "crash"
  - "error"
  - "not working"

documentation:
  - "documentation"
  - "docs"
  - "readme"

enhancement:
  - "feature"
  - "enhancement"
  - "improve"
  - "add"

good first issue:
  - "good first issue"
  - "beginner"
  - "easy"

GSSoC'25:
  - "gssoc"
  - "GSSoC'25"
  - "girlscript"

help wanted:
  - "help"
  - "support"
  - "wanted"

invalid:
  - "invalid"
  - "not valid"

question:
  - "question"
  - "how"
  - "what"

duplicate:
  - "duplicate"
  - "already exists"

Level 1:
  - "level 1"

Level 2:
  - "level 2"

Level3:
  - "level 3"

wontfix:
  - "wontfix"
  - "will not fix"
