needs-screenshot:
  - any: ['**/*.css', '**/*.scss', '**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '**/*.html']

enhancement:
  - any: ['features/**', 'src/feature/**', 'src/components/**']

Development:
  - any: ['**/src/**', '**/frontend/**', '**/backend/**', '**/components/**']

"Level 2":
  - any: ['features/**', 'src/feature/**', 'src/components/**']

major-work:
  - any: ['src/core/**', 'server/**', 'api/**']

"Level 3":
  - any: ['src/core/**', 'server/**', 'api/**']

documentation:
  - any: ['**/*.md', 'docs/**']

bug:
  - any: ['**/bug/**', '**/bugs/**']

duplicate:
  - any: ['**/duplicate/**']

"good first issue":
  - any: ['**/good-first-issue/**']

"help wanted":
  - any: ['**/help-wanted/**']

invalid:
  - any: ['**/invalid/**']

question:
  - any: ['**/question/**', '**/questions/**']

wontfix:
  - any: ['**/wontfix/**']

"GSSoC'25":
  - any: ['**/*']
