# --- Pull Request Rules ---

# Screenshot reminder for UI-related changes
needs-screenshot:
  - '**/*.css'
  - '**/*.scss'
  - '**/*.js'
  - '**/*.jsx'
  - '**/*.ts'
  - '**/*.tsx'
  - '**/*.html'

# Documentation changes
documentation:
  - '**/*.md'
  - 'docs/**'

# Enhancements / feature improvements
enhancement:
  - 'features/**'
  - 'src/feature/**'

# Major work / new features
major-work:
  - 'src/core/**'
  - 'server/**'
  - 'api/**'

# Assign levels based on type of work
Level 1:
  - 'pull_request:labels:documentation'
Level 2:
  - 'pull_request:labels:enhancement'
Level 3:
  - 'pull_request:labels:major-work'

# --- Issue Rules ---

# Bug reports (title starts with [BUG])
bug:
  - 'issues: ["^\\[BUG\\]"]'

# Feature requests (title starts with [Feature])
enhancement:
  - 'issues: ["^\\[Feature\\]"]'

# Questions
question:
  - 'issues: ["^\\[Question\\]"]'

# Invalid
invalid:
  - 'issues: ["\\[Invalid\\]"]'
