name: Bug Report
description: File a bug report if something isn't working as expected.
title: "[BUG] "
labels: bug
body:
  - type: textarea
    id: describe_bug
    attributes:
      label: "Describe the bug"
      description: "Clearly describe what went wrong."
      placeholder: "When I clicked login, the app crashed."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "List the steps to reproduce the bug."
      placeholder: |
        1. Open app
        2. Click login
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"
      placeholder: "The page should load normally."
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshot (optional)"
      description: "Add a screenshot if it helps explain the problem."
      placeholder: "Drag and drop an image here."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thank you for reporting this issue! We'll look into it as soon as possible.
