name: Bug Report
title: "[BUG] "
labels: bug
body:
  - type: textarea
    id: describe_bug
    attributes:
      label: "Describe the bug"
      description: "Tell us what you saw. This will be shown as a hint."
      placeholder: "When I clicked login, the app crashed."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How to see it happen
      description: Write the steps so we can repeat the bug.
      placeholder: "1. Open app\n2. Click login\n3. See error"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What you expected
      description: What should have happened instead?
      placeholder: "The page should load normally."
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot (optional)
      description: Add a screenshot if it helps show the problem.
      placeholder: "Drag and drop an image here."
    validations:
      required: false
