---
name: "🐞 Bug Report"
about: Report a bug or problem
title: "[BUG] "
labels: bug
---

## What happened?
Write in a few words what went wrong.

## How to see it happen
Steps to check the problem:
1. Go to ...
2. Click ...
3. See the problem

## What you expected
What should have happened?

## Screenshot (if possible)
Drag and drop a picture if it helps explain the problem.

## Anything else to tell us?
Add any extra info, like which device or browser you used.
