# .github/ISSUE_TEMPLATE/feature_request.yml
name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["feature"]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: What would you like to see added or changed?
      placeholder: Clear and concise description of the request.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If this feature affects the UI, please **include before/after screenshots**.
      placeholder: Drag and drop images here.
    validations:
      required: false
