name: Feature Request
title: "[Feature] "
labels: enhancement
body:
  - type: textarea
    id: feature_description
    attributes:
      label: What is the feature?
      description: Briefly describe the feature you want.
      placeholder: "Add a dark mode option for the app."
    validations:
      required: true

  - type: textarea
    id: why_needed
    attributes:
      label: Why is this feature needed?
      description: Explain why this would be useful.
      placeholder: "Dark mode helps users use the app at night."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: Add a screenshot or mockup if it helps explain the feature.
      placeholder: "Add image here."
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: Anything else?
      description: Add extra notes or details if needed.
      placeholder: "Extra info, references, or ideas."
    validations:
      required: false
