name: Deploy Frontend to Vercel

# This workflow is disabled by default and can only be triggered manually
# To enable automatic deployments:
# 1. Add the following secrets to your repository:
#    - VERCEL_TOKEN: Your Vercel authentication token
#    - ORG_ID: Your Vercel organization ID
#    - PROJECT_ID: Your Vercel project ID
# 2. Uncomment the 'push' trigger below and remove 'workflow_dispatch'

on:
  workflow_dispatch:  # Manual trigger only
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'frontend/**'

defaults:
  run:
    working-directory: ./frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./frontend
          vercel-args: '--prod'
